# map of keys from version 3 API to version 3.1 API
# note that this needs edited to clean up mappings as this didn't map 100%


{'inc_stmt': 
	{'revenue': 'revenue',
	  'revenueGrowth': 'revenueGrowth',
	  'costOfRevenue': 'costOfRevenue',
	  'grossProfit': 'grossProfit',
	  'r&dExpenses': 'researchAndDevelopmentExpenses',
	  'sg&aExpense': 'sellingGeneralAdministrativeExpenses',
	  'operatingExpenses': 'operatingExpenses',
	  'operatingIncome': 'operatingIncome',
	  'interestExpense': 'interestExpense',
      
	  'earningsBeforeTax': 'otherIncomeNet',
	  'incomeTaxExpense': 'earningsBeforeTax',
	  'netIncome-Non-controllingInt': 'incomeTaxExpense',
	  'netIncome-DiscontinuedOps': 'netIncomeNonControllingInterest',
	  'netIncome': 'netIncomeDiscontinuedOps',
	  'preferredDividends': 'netIncome',
	  'netIncomeCom': 'preferredDividends',
	  'ePS': 'netIncomeCom',
	  'epsDiluted': 'eps',
	  'weightedAverageShsOut': 'epsDiluted',
	  'weightedAverageShsOut(dil)': 'weigtedAverageSharesOutstanding',
	  'dividendPerShare': 'weigtedAverageSharesOutstandingDiluted',
	  'grossMargin': 'dividendPerShare',
	  'ebitdaMargin': 'grossMargin',
	  'ebitMargin': 'ebitdaMargin',
	  'profitMargin': 'ebitMargin',
	  'freeCashFlowMargin': 'profitMargin',
	  'eBITDA': 'freeCashFlowMargin',
	  'eBIT': 'ebitda',
	  'consolidatedIncome': 'ebit',
	  'earningsBeforeTaxMargin': 'consolidatedIncome',
	  'netProfitMargin': 'earningsBeforeTaxMargin'},
 'bal_sht': {'cashAndCashEquivalents': 'cashAndCashEquivalents',
	  'short-termInvestments': 'shortTermInvestments',
	  'cashAndShort-termInvestments': 'cashAndShortTermInvestments',
	  'receivables': 'receivables',
	  'inventories': 'inventories',
	  'totalCurrentAssets': 'totalCurrentAssets',
	  'property,Plant&EquipmentNet': 'propertyPlantAndEquipmentNet',
	  'goodwillAndIntangibleAssets': 'goodwillAndIntangibleAssets',
	  'long-termInvestments': 'longTermInvestments',
	  'taxAssets': 'taxAssets',
	  'totalNon-currentAssets': 'totalNonCurrentAssets',
	  'totalAssets': 'totalAssets',
	  'payables': 'payables',
	  'short-termDebt': 'shortTermDebt',
	  'totalCurrentLiabilities': 'totalCurrentLiabilities',
	  'long-termDebt': 'longTermDebt',
	  'totalDebt': 'totalDebt',
	  'deferredRevenue': 'deferredRevenue',
	  'taxLiabilities': 'taxLiabilities',
	  'depositLiabilities': 'depositLiabilities',
	  'totalNon-currentLiabilities': 'totalNonCurrentLiabilities',
	  'totalLiabilities': 'totalLiabilities',
	  'otherComprehensiveIncome': 'commonStockAndAdditionalPaidinCapital',
	  'retainedEarnings(deficit)': 'otherComprehensiveIncome',
	  'totalShareholdersEquity': 'retainedEarningsDeficit',
	  'investments': 'totalShareholdersEquity',
	  'netDebt': 'investments',
	  'otherAssets': 'netDebt',
	  'otherLiabilities': 'otherAssets'},
 'cf_stmt': {'depreciation&Amortization': 'netIncome',
	  'stock-basedCompensation': 'cashAndCashEquivalentsBeginingPeriod',
	  'operatingCashFlow': 'depreciationAndAmortization',
	  'capitalExpenditure': 'stockBasedCompensation',
	  'acquisitionsAndDisposals': 'operatingCashFlow',
	  'investmentPurchasesAndSales': 'capitalExpenditure',
	  'investingCashFlow': 'acquisitionsAndDisposals',
	  'issuance(repayment)OfDebt': 'investmentPurchasesAndSales',
	  'issuance(buybacks)OfShares': 'investingCashFlow',
	  'dividendPayments': 'issuanceOrRepaymentOfDebt',
	  'financingCashFlow': 'issuanceBuybacksOfShares',
	  'effectOfForexChangesOnCash': 'dividendPayments',
	  'netCashFlow/ChangeInCash': 'financingCashFlow',
	  'freeCashFlow': 'effectOfForexChangesOnCash',
	  'netCash/marketcap': 'freeCashFlow'}}